### ISSUE TITLE
css lost when submit an empty form.

### ISSUE THREAD

**Issue by rainasmoon** [spring-projects/spring-petclinic#45] opened 2014-06-04 15:04 UTC
Hi does any one face this issue? if i click on add a user button but without input any field then the css will lost?

**Comment by michaelisvy** [comment] 2015-05-20 14:21
I can't reproduce it either. I'm closing this issue. Please feel free to reopen in case you're still having an issue.

**Closed by michaelisvy** 2015-05-20 14:21 UTC
