### ISSUE TITLE
Could not find artifact me.n4u.sass:sass-gems:jar:3.1.19 after running ./mvnw package

### ISSUE THREAD

**Issue by seanlaii** [spring-projects/spring-petclinic#696] opened 2020-10-27 11:00 UTC
Hello every one, I get the error after running ./mvnw package. I have tried both JDK11 and JDK8, however, the error is still the same. Please help me. Thanks in advance!

<img width="1738" alt="截圖 2020-10-27 下午6 56 48" src="https://user-images.githubusercontent.com/30234478/97292467-3f342b80-1886-11eb-8949-3fe82d3e93e6.png">

**Comment by snicoll** [comment] 2020-11-06 07:14
We just upgraded to wro4j 1.9.0 so whatever project that's building in your screenshot didn't represent the state of master. I cannot reproduce the problem you're experiencing so I am going to close this now but we can reconsider if you share more details or a `sha` of this project that fails consistently.

**Closed by snicoll** 2020-11-06 07:14 UTC
